"""
Fin-Guard Analytics – Slack Alert Dispatcher
==============================================
Formats and sends rich Slack Block Kit messages when KPI thresholds
are breached, and resolution messages when they recover.
"""

from __future__ import annotations

import httpx
from datetime import datetime, timezone
from loguru import logger

from agent.config import settings
from agent.monitor import ThresholdBreach


SEVERITY_EMOJI = {
    "WARNING":  "⚠️",
    "CRITICAL": "🚨",
}

SEVERITY_COLOR = {
    "WARNING":  "#F0A500",
    "CRITICAL": "#E53E3E",
}


class SlackNotifier:
    """Sends alerts to Slack using Incoming Webhooks (Block Kit format)."""

    def __init__(self) -> None:
        self._webhook = settings.slack_webhook_url

    def _post(self, payload: dict) -> bool:
        if not self._webhook:
            logger.warning("[Slack] No webhook URL configured – skipping notification.")
            return False
        try:
            resp = httpx.post(self._webhook, json=payload, timeout=10)
            resp.raise_for_status()
            logger.success(f"[Slack] Alert sent (HTTP {resp.status_code})")
            return True
        except Exception as exc:
            logger.error(f"[Slack] Failed to send alert: {exc}")
            return False

    # ── Alert Message ────────────────────────────────────────────────────────

    def send_alert(self, breach: ThresholdBreach, investigation_summary: str) -> bool:
        """Send a formatted KPI breach alert to Slack."""
        emoji    = SEVERITY_EMOJI.get(breach.severity, "🚨")
        color    = SEVERITY_COLOR.get(breach.severity, "#E53E3E")
        ts_now   = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        payload = {
            "channel": settings.slack_channel,
            "attachments": [
                {
                    "color": color,
                    "blocks": [
                        {
                            "type": "header",
                            "text": {
                                "type": "plain_text",
                                "text": f"{emoji} Fin-Guard Alert: {breach.severity} – {breach.kpi_name}",
                            },
                        },
                        {"type": "divider"},
                        {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": f"*KPI:*\n{breach.kpi_name}",
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Severity:*\n{breach.severity}",
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Current Value:*\n`{breach.current_value:.4f}`",
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Threshold:*\n`{breach.threshold}`",
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Detected At:*\n{ts_now}",
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": f"*Direction:*\n{breach.direction.upper()}",
                                },
                            ],
                        },
                        {"type": "divider"},
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": f"*🔍 AI Root-Cause Analysis:*\n{investigation_summary[:2900]}",
                            },
                        },
                        {
                            "type": "context",
                            "elements": [
                                {
                                    "type": "mrkdwn",
                                    "text": "🤖 Generated by Fin-Guard Agentic AI Monitor | Powered by GPT-4",
                                }
                            ],
                        },
                    ],
                }
            ],
        }

        return self._post(payload)

    # ── Resolution Message ────────────────────────────────────────────────────

    def send_resolution(self, kpi_name: str, current_value: float, threshold: float) -> bool:
        """Send a Slack notification when a KPI returns below threshold."""
        ts_now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        payload = {
            "channel": settings.slack_channel,
            "attachments": [
                {
                    "color": "#38A169",
                    "blocks": [
                        {
                            "type": "header",
                            "text": {
                                "type": "plain_text",
                                "text": f"✅ Fin-Guard: KPI Resolved – {kpi_name}",
                            },
                        },
                        {
                            "type": "section",
                            "fields": [
                                {"type": "mrkdwn", "text": f"*KPI:*\n{kpi_name}"},
                                {"type": "mrkdwn", "text": f"*Current Value:*\n`{current_value:.4f}`"},
                                {"type": "mrkdwn", "text": f"*Threshold:*\n`{threshold}`"},
                                {"type": "mrkdwn", "text": f"*Resolved At:*\n{ts_now}"},
                            ],
                        },
                    ],
                }
            ],
        }
        return self._post(payload)
